## Java 异常处理
#### Java Exception 和 Error
Exception 和 Error 都是继承了 Throwable 类，在 Java 中只有 Throwable 类型的的实例才可以被抛出 （throw）或者捕获（catch），它是异常处理机制的基本组成类型。

##### Exception
Exception(异常)又分为可检查异常和不可以检查异常，可检查异常在源代码里必须显式地进行捕获处理，这是编译器检查的一部分。
不检查的异常就是所谓的运行时异常，类似 NullPointerException，ArrayIndexOutOfBoundsException之类，通常是可以编码避免的逻辑错误，具体根据需要来判断是否需要捕获，并不是编译期强制要求。

##### Error
Error 是指在正常情况下，不大可能出现的情况，绝大多数的 Error 都会导致程序（比如 JVM 自身）处于非正常的，不可以恢复的状态。

#### 异常
##### 异常丢失

```
public class VeryImportanrException extends Exception {
    public String toString() {
        return "A very important exception!";
    }
}

public class HoHumException extends Exception {
    public String toString() {
        return "A very HoHumException exception!";
    }
}

public class LostMessage {

    void f() throws VeryImportanrException {
        throw new VeryImportanrException();
    }

    void dispose() throws HoHumException {
        throw new HoHumException();
    }

    public static void main(String[] args) {

        try {
            LostMessage lm = new LostMessage();
            try {
                lm.f();
            } finally {
                lm.dispose();
            }
        } catch (Exception e) {
            System.out.println(e);
        }

    }

}

```

从以上代码可以看出，在同一个异常处理代码块里面，如果有两个异常的话，上一个异常未被处理，会被下一个异常覆盖。

##### 异常限制
当方法覆盖的时候，只能抛出在基类方法的异常说明里列出的那些异常。

##### 异常匹配

```
package ExceptionMatch;
class Annoyance extends Exception {}
class Sneeze extends Annoyance {}

public class Human {

    public static void main(String[] args) {

        try {
            throw new Sneeze();
        } catch (Sneeze z) {
            System.out.println("Caught Sneeze");
        } catch (Annoyance a) {
            System.out.println("Caught Annoyance");
        }

        try {
            throw new Sneeze();
        } catch (Annoyance e) {
            System.out.println("1Caught Annoyance");
        }

    }
}
```

抛出异常的时候，异常处理系统会按照代码的书写顺序找出"最近"的处理程序。找到匹配的处理程序之后，它就认为异常将得到处理，然后就不在继续查找。Sneeze 异常会被第一个匹配的 catch 子句捕获，也就是程序里的第一个。如果将 catch 子句删除，只留下 Annoyance catch子句，该程序仍然能运行，因为这次捕获的是 Sneeze 的基类。换句话说，catch(Annoyance) 会捕获 Annoyance 以及所有从它派生的异常。这一点非常有用，因为如果决定在方法里加上更多派生异常的话，只要捕获的是基类异常，那么他们的代码就无须更改。

##### try-catch-finally
try 里面即使有 return 也是会执行 finally。但是有一种特殊情况 try 里面放入System.exit(1) finally 则不会执行，这个要从操作系统层面说起了。
